### ISSUE TITLE
Fails on non-ASCII characters in SQL comments

### ISSUE THREAD

**Issue by sashka** [yandex/pgmigrate#1]
Migration fails on German or Russian letters in SQL comments with this message:

```pgmigrate.MalformedStatement: Non ascii symbols in file: migrations/V0005__initial_companies.sql, 'ascii' codec can't encode characters in position 447-451: ordinal not in range(128)```

When comments are removed it works again.

**Comment by man-brain** [comment]
Actually, it's not a bug, it's a feature :) We even have [a test](https://github.com/yandex/pgmigrate/blob/21849625b2363c5c35478974c4bf3bbc35ab3628/features/errors_handle.feature#L38-L47) for that. Because generally it brings more problems than benefits.

But if you do really want it, you can workaround it in the [following way](https://github.com/yandex/pgmigrate/blob/21849625b2363c5c35478974c4bf3bbc35ab3628/features/modeline.feature).

**Comment by sashka** [comment]
Got that. It would be great to have it in documentation. I'll get back with PR for that soon.
Thank you.
