### ISSUE TITLE
No additional logging when using `--verbose`

### ISSUE THREAD

**Issue by neothor** [yandex/pgmigrate#25]
I am implementing pgmigrate inside a docker container. It is executing all version script perfectly but when using the `--verbose` flag I don't get any additional logging.

I am using the environment variables to pass in the connection details and use the following command.
`pgmigrate --verbose -c '' -t latest migrate`

Using 1.0.6
```bash
bash-5.1# pip show yandex-pgmigrate
Name: yandex-pgmigrate
Version: 1.0.6
Summary: PostgreSQL migrations made easy
Home-page: https://github.com/yandex/pgmigrate/
Author: Yandex LLC
Author-email: opensource@yandex-team.ru
License: PostgreSQL License
Location: /usr/local/lib/python3.9/site-packages
Requires: PyYAML, sqlparse, psycopg2
Required-by:
```

usage
```bash
echo "executing migration"
pgmigrate --verbose -c '' -t latest migrate

echo 
echo "----------- 📋 results -----------"
```

results
```bash
executing migration

----------- 📋 results -----------
```

**Comment by secwall** [comment]
Actually, this is expected behavior.
The default log level is `ERROR`. Adding one `--verbose` option moves it to `WARNING`.
So if there are no warnings (e.g. no garbage files in migrations dir) no more additional logs would be emitted.
You could try using `-vv` or `--verbose --verbose` for `INFO` log level or even `-vvv` for `DEBUG`.

**Comment by neothor** [comment]
👍 excellent I will update the code accordingly.
